# Generated by Django 4.2.17 on 2025-01-11 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sales_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
