# Generated by Django 4.2.17 on 2025-01-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_user_inventory_created_by_alter_sales_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product_sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='myapp.inventory'),
        ),
    ]
