# Generated by Django 4.2.16 on 2024-10-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product',
            new_name='product_sold',
        ),
    ]
